use_frameworks!

target 'ContactCircularView_Example' do
  pod 'ContactCircularView', :path => '../'

  target 'ContactCircularView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
