use_frameworks!

target 'ContactCircularView_Example' do
  pod 'ContactCircularView', :path => '../'
  pod 'PureLayout', '~> 3.0'

  target 'ContactCircularView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.10'
  	pod 'Nimble', '~> 5.0'
  end

  post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

end
